# Generated by Django 4.1.3 on 2022-11-26 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publication',
            new_name='publications',
        ),
    ]
