# Generated by Django 4.1.3 on 2022-11-28 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HogarPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_raza', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('fecha_adopcion', models.DateField(blank=True, null=True)),
                ('estado_mascota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mascotas.estadomascota')),
                ('hogar_paso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mascotas.hogarpaso')),
                ('raza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mascotas.raza')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
        ),
    ]
