# Generated by Django 4.1.3 on 2022-11-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_registro',
            new_name='fecha',
        ),
    ]
