# Generated by Django 4.1.3 on 2022-11-28 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_fecha_registro_usuario_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha',
            new_name='fecha_registro',
        ),
    ]
