# Generated by Django 4.1.3 on 2022-11-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_registro',
        ),
    ]
