# Generated by Django 4.1.3 on 2022-11-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytoone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='email',
            field=models.EmailField(default='mono', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporter',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
    ]
