# Generated by Django 4.1.3 on 2022-11-28 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_contactos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=12)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='Contactos',
        ),
    ]
